name: Build

on:
  push:

jobs:
  build-lint-test:
    runs-on: ubuntu-latest

    container:
      image: cimg/node:20.5.1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Check code format
        run: |
          npm run fmt
          git --no-pager diff
          exit $(git diff | wc -l)

      - name: Check commit message format
        run: npx commitlint --from=main

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm run test

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: jest-junit-report
          path: reports/jest-junit

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: reports
          path: reports
